service: icybemind
runtime: php55
api_version: 1
env: standard
threadsafe: false

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: 3000ms
  max_concurrent_requests: 80

instance_class: F1

handlers:

- url: /index.html
  static_files: /index.html
  upload: /index.html

- url: /
  static_dir: /


skip_files:
    
- media/hexscans/Desktop Text Data
- .git/

