service: icybemind
runtime: php55
api_version: 1
env: standard
threadsafe: false

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 30ms
  max_pending_latency: 3000ms
  max_concurrent_requests: 80

instance_class: F1

handlers:

  - url: /index.html
    static_files: index.html
    upload: index.html

  - url: /(.*)\.php$
    script: \1.php

  - url: /(.*)
    static_files: \1
    upload: /(.*)

  - url: /(.*)
    static_dir: \1


skip_files:
    
- media/hexscans/Desktop Text Data
- .git/

